services:
  my-server:
    image: ${AWS_IMAGE_URL} # 도커허브 링크로 가지는거 문제 없는지 체크필요함 (체크완료, 문제없음 )
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql-server:
        condition: service_healthy
      my-cache-server:
        condition: service_healthy