spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}

  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: ${DATABASE_PLATFORM}
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port:${SERVER_PORT}


logging:
  level:
    root: debug                     # 모든 패키지에 대해 디버그 레벨 로그 출력
    org.springframework.cache: trace  # Redis 캐시 사용 추적
    org.hibernate.SQL: debug          # SQL 쿼리 로그 (개발용)
    org.hibernate.orm.jdbc.bind: debug # SQL 바인딩 로그는 디버그 수준으로
    org.springframework.web: debug    # Spring MVC 관련 로그
    org.thymeleaf: debug              # Thymeleaf 템플릿 디버깅 (템플릿 엔진 사용 시)
    com.example: trace                # 내가 개발한 패키지에 대해 trace 레벨
  file:
    name: logs/local-app.log          # 로컬 로그 파일 경로
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 콘솔 출력 포맷
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"              # 파일 출력 포맷





