## prod 설정
spring:
  datasource:
    url: ${DEV_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: none 으로 바꿀 생각하기.
    database-platform: ${DATABASE_PLATFORM}
    properties:
      hibernate:
        format_sql: true


server:
  port:${SERVER_PORT}



