## dev 설정
spring:
  datasource:
    url: ${DEV_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
    hikari:
      maximumPoolSize: 5        # 적은 커넥션 풀 크기 설정
      idleTimeout: 30000        # 비활성 커넥션의 유지 시간 단축
      connectionTimeout: 20000  # 커넥션 대기 시간 단축

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${DATABASE_PLATFORM}
    properties:
      hibernate:
        format_sql: true


server:
  port:${SERVER_PORT}